export type QuestionManifestItem = {
  question: number;
  slug: string;
  title: string;
  chapter: string;
  difficulty: "easy" | "medium" | "hard";
  difficultyScore: number;
  durationBudgetSeconds: number;
  visualTemplate: string;
  status: "in-progress" | "complete";
};

export const QUESTION_MANIFEST: QuestionManifestItem[] = [
  {
    question: 1,
    slug: "static",
    title: "static 关键字有哪些作用？",
    chapter: "C/C++ 基础",
    difficulty: "hard",
    difficultyScore: 8,
    durationBudgetSeconds: 285,
    visualTemplate: "code-memory",
    status: "complete",
  },
  {
    question: 2,
    slug: "const",
    title: "const 关键字有什么作用？",
    chapter: "C/C++ 基础",
    difficulty: "medium",
    difficultyScore: 6,
    durationBudgetSeconds: 240,
    visualTemplate: "code-compare",
    status: "complete",
  },
  {
    question: 3,
    slug: "volatile",
    title: "volatile 关键字在嵌入式开发中有什么作用？",
    chapter: "C/C++ 基础",
    difficulty: "hard",
    difficultyScore: 8,
    durationBudgetSeconds: 270,
    visualTemplate: "event-visibility",
    status: "complete",
  },
  {
    question: 4,
    slug: "extern",
    title: "extern 关键字有什么作用？",
    chapter: "C/C++ 基础",
    difficulty: "medium",
    difficultyScore: 6,
    durationBudgetSeconds: 240,
    visualTemplate: "linkage-graph",
    status: "complete",
  },
  {
    question: 5,
    slug: "array-pointer",
    title: "指针和数组有什么区别？",
    chapter: "C/C++ 基础",
    difficulty: "hard",
    difficultyScore: 8,
    durationBudgetSeconds: 270,
    visualTemplate: "memory-compare",
    status: "complete",
  },
  {
    question: 6,
    slug: "pointer-reference",
    title: "指针和引用有什么区别？",
    chapter: "C/C++ 基础",
    difficulty: "medium",
    difficultyScore: 6,
    durationBudgetSeconds: 240,
    visualTemplate: "pointer-reference-state",
    status: "complete",
  },
  {
    question: 7,
    slug: "sizeof-strlen",
    title: "sizeof 和 strlen 有什么区别？",
    chapter: "C/C++ 基础",
    difficulty: "medium",
    difficultyScore: 6,
    durationBudgetSeconds: 240,
    visualTemplate: "sizeof-strlen-buffer",
    status: "complete",
  },
  {
    question: 8,
    slug: "heap-stack",
    title: "堆和栈有什么区别？",
    chapter: "C/C++ 基础",
    difficulty: "medium",
    difficultyScore: 6,
    durationBudgetSeconds: 240,
    visualTemplate: "stack-heap-lifecycle",
    status: "complete",
  },
  {
    question: 9,
    slug: "global-local-static",
    title: "全局变量、局部变量和静态变量分别存放在哪里？",
    chapter: "C/C++ 基础",
    difficulty: "medium",
    difficultyScore: 6,
    durationBudgetSeconds: 240,
    visualTemplate: "storage-map-startup",
    status: "complete",
  },
  {
    question: 10,
    slug: "malloc-new",
    title: "malloc/free 和 new/delete 有什么区别？",
    chapter: "C/C++ 基础",
    difficulty: "medium",
    difficultyScore: 6,
    durationBudgetSeconds: 240,
    visualTemplate: "allocation-lifecycle-compare",
    status: "complete",
  },
  {
    question: 11,
    slug: "delete-array",
    title: "delete 和 delete[] 有什么区别？",
    chapter: "C/C++ 基础",
    difficulty: "medium",
    difficultyScore: 6,
    durationBudgetSeconds: 240,
    visualTemplate: "delete-array-lifecycle",
    status: "complete",
  },
  {
    question: 12,
    slug: "memory-leak",
    title: "什么是内存泄漏？如何避免？",
    chapter: "C/C++ 基础",
    difficulty: "medium",
    difficultyScore: 6,
    durationBudgetSeconds: 240,
    visualTemplate: "memory-leak-ownership",
    status: "complete",
  },
];
