import { AbsoluteFill, Composition, Easing, interpolate, Sequence, useCurrentFrame } from "remotion";
import type { CSSProperties, ReactNode } from "react";

const FPS = 30;
const seconds = (value: number) => Math.round(value * FPS);
const COLORS = {
  background: "#eef2f4",
  surface: "rgba(255, 255, 255, 0.72)",
  strong: "rgba(255, 255, 255, 0.90)",
  text: "#100f0f",
  muted: "#6f6e69",
  faint: "#9b9a97",
  border: "rgba(22, 30, 38, 0.11)",
  accent: "#d87757",
  active: "#087f8c",
  result: "#198754",
  danger: "#c2413b",
  compare: "#b45309",
  violet: "#6f65b8",
};
const BODY_FONT = 'Inter, "PingFang SC", "Noto Sans SC", system-ui, sans-serif';
const DISPLAY_FONT = 'Iowan Old Style, "Songti SC", STSong, Georgia, serif';
const CODE_FONT = '"Fira Code", "SFMono-Regular", Menlo, Consolas, monospace';
const ease = Easing.bezier(0.22, 1, 0.36, 1);
const SCENE = {
  opening: seconds(18),
  map: seconds(22),
  link: seconds(55),
  errors: seconds(32),
  cpp: seconds(25),
  followups: seconds(48),
  final: seconds(34),
} as const;
const TOTAL_FRAMES = Object.values(SCENE).reduce((sum, value) => sum + value, 0);

const clamp = (value: number, start: number, end: number) => interpolate(value, [start, end], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: ease });
const reveal = (frame: number, start = 0, distance = 16): CSSProperties => {
  const immediate = start <= 0;
  const from = immediate ? 0 : start;
  return {
    opacity: interpolate(frame, [from, from + 24], immediate ? [0.9, 1] : [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: ease }),
    transform: `translateY(${interpolate(frame, [from, from + 24], immediate ? [3, 0] : [distance, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: ease })}px)`,
  };
};

const Card: React.FC<{ children: ReactNode; style?: CSSProperties; strong?: boolean }> = ({ children, style, strong }) => <div style={{ border: `1px solid ${COLORS.border}`, borderRadius: 8, backgroundColor: strong ? COLORS.strong : COLORS.surface, boxShadow: "0 16px 48px rgba(22, 30, 38, 0.10)", ...style }}>{children}</div>;
const Background: React.FC = () => <><div style={{ position: "absolute", inset: 0, backgroundColor: COLORS.background, backgroundImage: "linear-gradient(rgba(8, 127, 140, 0.035) 1px, transparent 1px), linear-gradient(90deg, rgba(8, 127, 140, 0.035) 1px, transparent 1px), linear-gradient(135deg, rgba(255,255,255,0.42), rgba(238,242,244,0.18))", backgroundSize: "48px 48px, 48px 48px, 100% 100%" }} /><div style={{ position: "absolute", left: -180, top: 80, width: 760, height: 760, borderRadius: 180, backgroundColor: "rgba(255, 255, 255, 0.28)", transform: "rotate(-16deg)", filter: "blur(12px)" }} /><div style={{ position: "absolute", right: -240, bottom: -260, width: 760, height: 680, borderRadius: 220, backgroundColor: "rgba(216, 119, 87, 0.075)", transform: "rotate(18deg)", filter: "blur(16px)" }} /></>;
const TopBar: React.FC<{ frame: number; section: string; title: string; tag?: string }> = ({ frame, section, title, tag = "慢速复习 · 3:54" }) => <Card strong style={{ position: "absolute", left: 58, right: 58, top: 26, minHeight: 62, padding: "0 20px", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 20, ...reveal(frame) }}><div style={{ display: "flex", alignItems: "center", gap: 14, minWidth: 0 }}><div style={{ color: COLORS.accent, fontFamily: CODE_FONT, fontSize: 13, fontWeight: 800 }}>C / C++ 基础</div><div style={{ width: 1, height: 18, backgroundColor: COLORS.border }} /><div style={{ color: COLORS.text, fontSize: 18, fontWeight: 760, whiteSpace: "nowrap" }}>{section}</div><div style={{ color: COLORS.muted, fontSize: 16, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{title}</div></div><div style={{ flex: "0 0 auto", padding: "8px 11px", border: `1px solid ${COLORS.border}`, borderRadius: 6, color: COLORS.muted, fontFamily: CODE_FONT, fontSize: 12, fontWeight: 700 }}>{tag}</div></Card>;
const Caption: React.FC<{ frame: number; label: string; title: string; body: string; color?: string }> = ({ frame, label, title, body, color = COLORS.active }) => <Card strong style={{ position: "absolute", left: 58, right: 58, bottom: 54, minHeight: 106, padding: "15px 20px 16px", borderTop: `3px solid ${color}`, ...reveal(frame) }}><div style={{ display: "flex", justifyContent: "space-between", color: COLORS.muted, fontFamily: CODE_FONT, fontSize: 11, fontWeight: 800 }}><span>{label}</span><span>先理解，再记忆</span></div><div style={{ marginTop: 8, color: COLORS.text, fontSize: 22, fontWeight: 800 }}>{title}</div><div style={{ marginTop: 5, color: COLORS.muted, fontSize: 15, lineHeight: 1.45 }}>{body}</div></Card>;
const SceneTitle: React.FC<{ frame: number; eyebrow: string; title: string; detail: string }> = ({ frame, eyebrow, title, detail }) => <div style={{ position: "absolute", left: 72, right: 72, top: 122, ...reveal(frame) }}><div style={{ color: COLORS.accent, fontFamily: CODE_FONT, fontSize: 14, fontWeight: 800, letterSpacing: 1.3 }}>{eyebrow}</div><div style={{ marginTop: 10, color: COLORS.text, fontFamily: DISPLAY_FONT, fontSize: 44, fontWeight: 700, lineHeight: 1.16 }}>{title}</div><div style={{ marginTop: 9, color: COLORS.muted, fontSize: 18, lineHeight: 1.45 }}>{detail}</div></div>;
const Prompt: React.FC<{ frame: number; question: string; seconds: number; color?: string; hint?: string }> = ({ frame, question, seconds: duration, color = COLORS.active, hint = "先在脑中说一遍，再看标准说法" }) => { const remaining = Math.max(0, Math.ceil((duration * FPS - frame) / FPS)); const progress = clamp(frame, 0, duration * FPS); return <Card strong style={{ width: 670, minHeight: 290, padding: "28px 32px", borderLeft: `4px solid ${color}`, ...reveal(frame, 0, 20) }}><div style={{ color, fontFamily: CODE_FONT, fontSize: 13, fontWeight: 800, letterSpacing: 1.2 }}>先暂停 · 主动回忆</div><div style={{ marginTop: 20, color: COLORS.text, fontFamily: DISPLAY_FONT, fontSize: 33, fontWeight: 700, lineHeight: 1.28 }}>{question}</div><div style={{ display: "flex", alignItems: "center", gap: 18, marginTop: 26 }}><div style={{ color, fontFamily: CODE_FONT, fontSize: 44, fontWeight: 800, minWidth: 54 }}>{remaining}</div><div style={{ color: COLORS.muted, fontSize: 16, lineHeight: 1.45 }}>{hint}</div></div><div style={{ height: 6, marginTop: 24, borderRadius: 999, backgroundColor: COLORS.border }}><div style={{ height: "100%", width: `${progress * 100}%`, borderRadius: 999, backgroundColor: color }} /></div></Card>; };
const CodePanel: React.FC<{ title: string; lines: string[]; activeLine?: number; style?: CSSProperties }> = ({ title, lines, activeLine = -1, style }) => <Card strong style={{ overflow: "hidden", backgroundColor: "rgba(247,248,249,0.92)", ...style }}><div style={{ height: 44, display: "flex", alignItems: "center", gap: 8, padding: "0 16px", borderBottom: `1px solid ${COLORS.border}`, color: COLORS.muted, fontFamily: CODE_FONT, fontSize: 12, fontWeight: 750 }}><span style={{ width: 8, height: 8, borderRadius: 999, backgroundColor: COLORS.danger }} /><span style={{ width: 8, height: 8, borderRadius: 999, backgroundColor: COLORS.compare }} /><span style={{ width: 8, height: 8, borderRadius: 999, backgroundColor: COLORS.result }} /><span style={{ marginLeft: 8 }}>{title}</span></div><div style={{ padding: "18px 18px", fontFamily: CODE_FONT, fontSize: 20, lineHeight: 1.75 }}>{lines.map((line, index) => { const active = index === activeLine; return <div key={`${title}-${index}`} style={{ display: "flex", minHeight: 34, padding: "0 10px", borderRadius: 5, backgroundColor: active ? `${COLORS.compare}16` : "transparent", color: active ? COLORS.text : index === 0 ? COLORS.muted : COLORS.text, opacity: activeLine >= 0 && index > activeLine + 2 ? 0.44 : 1 }}><span style={{ width: 31, color: active ? COLORS.compare : COLORS.faint, fontSize: 14 }}>{String(index + 1).padStart(2, "0")}</span><span style={{ whiteSpace: "pre" }}>{line}</span></div>; })}</div></Card>;
const Badge: React.FC<{ children: ReactNode; color: string }> = ({ children, color }) => <div style={{ display: "inline-flex", alignItems: "center", gap: 8, padding: "8px 11px", border: `1px solid ${color}55`, borderRadius: 6, backgroundColor: `${color}12`, color, fontFamily: CODE_FONT, fontSize: 12, fontWeight: 750 }}><span style={{ width: 7, height: 7, borderRadius: 999, backgroundColor: color }} />{children}</div>;

const Opening: React.FC = () => { const frame = useCurrentFrame(); const done = frame >= seconds(6); const cards = [["01", "声明 vs 定义", "谁分配存储空间？", COLORS.accent], ["02", "多文件符号", "sensor.c、sensor.h、main.c 怎么连起来？", COLORS.active], ["03", "链接边界", "重复定义、未定义、extern C", COLORS.result]] as const; return <AbsoluteFill><TopBar frame={frame} section="第 4 题" title="extern 关键字有什么作用？" /><SceneTitle frame={frame} eyebrow="复习目标" title="先判断：这行代码到底创建了什么？" detail="extern 的难点不是背‘跨文件’，而是分清声明、定义、链接和工程边界。" /><div style={{ position: "absolute", left: 72, top: 304, right: 72, display: "flex", gap: 26, alignItems: "stretch" }}><Prompt frame={frame} question="extern 是声明还是定义？" seconds={6} color={COLORS.active} hint="先说：分不分配空间、符号在哪里、谁负责链接" /><Card strong style={{ flex: 1, padding: "28px 30px", opacity: done ? 1 : 0.42, transform: `translateX(${done ? 0 : 18}px)` }}><div style={{ color: COLORS.muted, fontFamily: CODE_FONT, fontSize: 13, fontWeight: 800, letterSpacing: 1.2 }}>本题路线</div><div style={{ marginTop: 22, display: "grid", gap: 16 }}>{cards.map(([number, label, detail, color]) => <div key={number} style={{ display: "grid", gridTemplateColumns: "44px 1fr", gap: 12, alignItems: "center", padding: "12px 14px", border: `1px solid ${COLORS.border}`, borderRadius: 8, backgroundColor: `${color}0b` }}><div style={{ color, fontFamily: CODE_FONT, fontSize: 15, fontWeight: 800 }}>{number}</div><div><div style={{ color: COLORS.text, fontSize: 20, fontWeight: 800 }}>{label}</div><div style={{ marginTop: 4, color: COLORS.muted, fontSize: 14 }}>{detail}</div></div></div>)}</div></Card></div><Caption frame={frame} label="本题总纲" title="extern 只告诉编译器‘符号在别处’，定义仍然要在工程中出现" body="先分清声明和定义，再看头文件与链接器如何把多个编译单元接起来。" /></AbsoluteFill>; };

const MAP = [["定义", "int g_temp_value = 0;", "分配空间，创建实体", COLORS.accent], ["变量声明", "extern int g_temp_value;", "不分配空间，只说明存在", COLORS.active], ["函数声明", "extern void read_sensor(void);", "函数声明通常省略 extern", COLORS.result]] as const;
const MapScene: React.FC = () => { const frame = useCurrentFrame(); return <AbsoluteFill><TopBar frame={frame} section="第 4 题" title="extern 的三层判断" /><SceneTitle frame={frame} eyebrow="答案地图" title="定义创建实体，声明连接名字" detail="变量和函数都可以跨文件使用，但‘谁分配存储’必须在工程里有且只有合适的一处。" /><div style={{ position: "absolute", left: 72, right: 72, top: 306, display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 18 }}>{MAP.map(([title, code, detail, color], index) => <Card key={title} strong style={{ minHeight: 290, padding: "26px 24px", borderTop: `4px solid ${color}`, ...reveal(frame, index * 26, 22) }}><div style={{ color, fontFamily: CODE_FONT, fontSize: 12, fontWeight: 800 }}>{String(index + 1).padStart(2, "0")}</div><div style={{ marginTop: 22, color: COLORS.text, fontFamily: DISPLAY_FONT, fontSize: 31, fontWeight: 700 }}>{title}</div><div style={{ marginTop: 28, padding: "12px 14px", borderRadius: 6, backgroundColor: `${color}10`, color, fontFamily: CODE_FONT, fontSize: 16 }}>{code}</div><div style={{ marginTop: 16, color: COLORS.muted, fontSize: 16, lineHeight: 1.45 }}>{detail}</div></Card>)}</div><Caption frame={frame} label="答案框架" title="extern 是声明，不是凭空创建变量" body="定义通常出现一次，声明可以在头文件中被多个编译单元看到；最终由链接器解析同一个符号。" /></AbsoluteFill>; };

const LINK_STATES = [["sensor.c 定义", "int g_temp_value = 0;", "真正创建全局实体并分配空间", COLORS.accent], ["sensor.h 声明", "extern int g_temp_value;", "头文件只把符号告诉使用者", COLORS.active], ["main.c 使用", "g_temp_value = 25;", "编译通过，等待链接器匹配定义", COLORS.compare], ["链接器解析", "sensor.o + main.o", "两个编译单元共享同一个符号", COLORS.result]] as const;
const LinkScene: React.FC = () => { const frame = useCurrentFrame(); const promptDone = frame >= seconds(7); const phase = promptDone ? Math.min(3, Math.floor((frame - seconds(7)) / seconds(12))) : -1; const activeLine = phase < 0 ? 0 : phase === 0 ? 0 : phase === 1 ? 1 : phase === 2 ? 2 : 3; return <AbsoluteFill><TopBar frame={frame} section="第 4 题 / 链接" title="多文件工程：一个定义，多个声明" /><SceneTitle frame={frame} eyebrow="确定性轨迹" title="名字跨文件可见，不等于空间被重复创建" detail="从 sensor.c 的定义出发，经过头文件声明，到 main.c 使用，最后由链接器完成符号匹配。" /><div style={{ position: "absolute", left: 72, right: 72, top: 300, height: 580, display: "grid", gridTemplateColumns: "0.9fr 1.1fr", gap: 22 }}><CodePanel title="multi_file.c" activeLine={activeLine} style={{ height: 500 }} lines={["int g_temp_value = 0;", "extern int g_temp_value;", "g_temp_value = 25;", "sensor.o + main.o -> g_temp_value", "// 声明不重复分配空间"]} /><Card strong style={{ padding: "24px 24px", position: "relative" }}><div style={{ color: COLORS.muted, fontFamily: CODE_FONT, fontSize: 12, fontWeight: 800 }}>符号链路 · 当前阶段 {phase < 0 ? "等待回忆" : `${phase + 1} / 4`}</div><div style={{ marginTop: 18, display: "grid", gap: 14 }}>{LINK_STATES.map(([title, code, detail, color], index) => { const active = index === phase; return <div key={title} style={{ padding: "15px 16px", border: `1px solid ${active ? color : COLORS.border}`, borderTop: `3px solid ${color}`, borderRadius: 7, backgroundColor: active ? `${color}12` : "rgba(255,255,255,0.52)", ...reveal(frame, 18 + index * 22) }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 14 }}><div style={{ color, fontFamily: CODE_FONT, fontSize: 17, fontWeight: 800 }}>{title}</div><Badge color={color}>{active ? "当前" : "轨迹"}</Badge></div><div style={{ marginTop: 10, color: COLORS.text, fontFamily: CODE_FONT, fontSize: 15 }}>{code}</div><div style={{ marginTop: 8, color: COLORS.muted, fontSize: 15, lineHeight: 1.4 }}>{detail}</div></div>; })}</div>{!promptDone && <div style={{ position: "absolute", inset: 22, display: "flex", alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,255,255,0.74)", borderRadius: 8 }}><Prompt frame={frame} question="头文件里的 extern 会分配空间吗？" seconds={7} color={COLORS.active} hint="先回答：声明、定义、编译、链接分别做什么" /></div>}</Card></div><Caption frame={frame} label="链接口诀" title="声明可以多次，定义要由工程提供合适的一次" body="extern 解决的是符号可见性和跨文件协作，不是把全局变量变成了更安全的接口。" /></AbsoluteFill>; };

const ErrorsScene: React.FC = () => { const frame = useCurrentFrame(); const promptDone = frame >= seconds(5); const rightActive = frame >= seconds(12); return <AbsoluteFill><TopBar frame={frame} section="第 4 题 / 错误" title="链接错误：重复定义和未定义符号" /><SceneTitle frame={frame} eyebrow="易错点" title="声明写错位置，错误会在链接阶段集中爆发" detail="头文件里直接定义、只声明不定义、多个源文件都定义，后果分别不同。" /><div style={{ position: "absolute", left: 72, right: 72, top: 306, display: "grid", gridTemplateColumns: "1fr 1fr", gap: 18 }}><Card strong style={{ minHeight: 490, padding: "26px 24px", borderTop: `4px solid ${COLORS.active}`, ...reveal(frame, 0) }}><div style={{ color: COLORS.active, fontFamily: CODE_FONT, fontSize: 12, fontWeight: 800 }}>三种错误</div><div style={{ marginTop: 20, display: "grid", gap: 12 }}>{["头文件直接写 int g_count = 0;：多重包含后重复定义", "只写 extern int g_count;：没有任何定义时未定义符号", "两个 .c 都定义 int g_count;：链接器发现重复定义"].map((line, index) => <div key={line} style={{ padding: "13px 14px", border: `1px solid ${COLORS.border}`, borderRadius: 6, color: index === 1 ? COLORS.compare : COLORS.text, fontSize: 16, fontWeight: index === 1 ? 700 : 600, opacity: promptDone ? 1 : 0.42 }}>{line}</div>)}</div></Card><Card strong style={{ minHeight: 490, padding: "26px 24px", borderTop: `4px solid ${COLORS.danger}`, ...reveal(frame, 18) }}><div style={{ color: COLORS.danger, fontFamily: CODE_FONT, fontSize: 12, fontWeight: 800 }}>错误发生在哪一步？</div><CodePanel title="linker.log" activeLine={rightActive ? 2 : 0} style={{ marginTop: 20, height: 225 }} lines={["compile main.c -> main.o", "compile sensor.c -> sensor.o", "link main.o + sensor.o", "error: duplicate / undefined symbol"]} /><div style={{ marginTop: 18, padding: "13px 14px", borderRadius: 6, backgroundColor: `${COLORS.danger}12`, color: COLORS.danger, fontSize: 16, fontWeight: 750 }}>编译器先检查每个文件，链接器再检查跨文件符号。</div></Card></div>{!promptDone && <div style={{ position: "absolute", left: 132, top: 370 }}><Prompt frame={frame} question="这三种 extern 错误，分别会在什么时候暴露？" seconds={5} color={COLORS.active} hint="先想：编译阶段还是链接阶段" /></div>}<Caption frame={frame} label="错误总结" title="看到 undefined / duplicate symbol，回到定义和声明的数量检查" body="工程中推荐由一个 .c 提供定义，头文件只提供 extern 声明，使用者只包含头文件。" color={COLORS.danger} /></AbsoluteFill>; };

const CppScene: React.FC = () => { const frame = useCurrentFrame(); const active = frame >= seconds(7); return <AbsoluteFill><TopBar frame={frame} section="第 4 题 / C++" title="extern C 与全局变量边界" /><SceneTitle frame={frame} eyebrow="语言边界" title="跨文件共享还要考虑链接约定和模块耦合" detail={'C++ 会对函数名做 name mangling；extern "C" 用来让 C++ 按 C 的链接约定导出接口。'} /><div style={{ position: "absolute", left: 72, right: 72, top: 306, display: "grid", gridTemplateColumns: "1fr 1fr", gap: 18 }}><Card strong style={{ minHeight: 490, padding: "26px 24px", borderTop: `4px solid ${COLORS.active}`, ...reveal(frame, 0) }}><div style={{ color: COLORS.active, fontFamily: CODE_FONT, fontSize: 12, fontWeight: 800 }}>C 与 C++ 的函数接口</div><div style={{ marginTop: 20, display: "grid", gap: 12 }}>{["C：read_sensor() 使用 C 链接约定", "C++：普通函数名可能被改编", "extern \"C\"：让 C++ 接口可被 C 调用"].map((line, index) => <div key={line} style={{ padding: "13px 14px", border: `1px solid ${COLORS.border}`, borderRadius: 6, color: index === 2 ? COLORS.active : COLORS.text, fontSize: 17, fontWeight: index === 2 ? 750 : 600, opacity: active ? 1 : 0.42 }}>{line}</div>)}</div></Card><Card strong style={{ minHeight: 490, padding: "26px 24px", borderTop: `4px solid ${COLORS.compare}`, ...reveal(frame, 18) }}><div style={{ color: COLORS.compare, fontFamily: CODE_FONT, fontSize: 12, fontWeight: 800 }}>全局变量的工程代价</div><div style={{ marginTop: 20, display: "grid", gap: 12 }}>{["多个模块都能改，调用链难追踪", "隐藏耦合增加，测试边界变模糊", "优先用函数接口和封装限制写权限"].map((line) => <div key={line} style={{ padding: "13px 14px", border: `1px solid ${COLORS.border}`, borderRadius: 6, color: COLORS.text, fontSize: 17, fontWeight: 600 }}>{line}</div>)}</div><div style={{ marginTop: 22, padding: "13px 14px", borderRadius: 6, backgroundColor: `${COLORS.compare}12`, color: COLORS.compare, fontSize: 16, fontWeight: 750 }}>extern 解决可见性，不自动解决设计质量。</div></Card></div><Caption frame={frame} label="工程边界" title="能跨文件访问，不等于应该到处暴露可写全局变量" body={'C++ 接口还要考虑 extern "C"；模块设计仍应优先通过函数和封装控制修改路径。'} color={COLORS.compare} /></AbsoluteFill>; };

const FOLLOWUPS = [["extern \"C\" 是干什么的？", "告诉 C++ 编译器使用 C 的链接约定，让 C 函数可以被 C++ 代码稳定调用。", COLORS.active], ["声明和定义有什么区别？", "声明告诉编译器符号存在，通常不分配空间；定义创建实体并分配所需空间。", COLORS.accent], ["extern 能用在函数上吗？", "可以，但函数声明默认具有外部链接语义，实际代码里通常省略 extern。", COLORS.result], ["为什么不推荐大量用全局变量？", "它会增加模块耦合、隐藏修改路径和测试成本，应该优先用接口封装。", COLORS.violet]] as const;
const FollowupScene: React.FC = () => { const frame = useCurrentFrame(); const index = Math.min(3, Math.floor(frame / seconds(12))); const local = frame - index * seconds(12); const answer = local >= seconds(5); const [question, explanation, color] = FOLLOWUPS[index]; return <AbsoluteFill><TopBar frame={frame} section="第 4 题 / 追问" title="面试官常问的四个边界问题" tag="慢速复习 · 0:48" /><SceneTitle frame={frame} eyebrow={`追问 ${index + 1} / 4`} title="先回答，再看标准说法" detail="每个追问先留 5 秒，答案只保留面试中真正需要说清的边界。" /><div style={{ position: "absolute", left: 72, right: 72, top: 302, display: "grid", gridTemplateColumns: "1.55fr 0.95fr", gap: 22 }}><Card strong style={{ minHeight: 570, padding: "34px 38px", borderLeft: `4px solid ${color}`, ...reveal(frame) }}><div style={{ color, fontFamily: CODE_FONT, fontSize: 13, fontWeight: 800, letterSpacing: 1.2 }}>INTERVIEW FOLLOW-UP</div><div style={{ marginTop: 26, color: COLORS.text, fontFamily: DISPLAY_FONT, fontSize: 35, fontWeight: 700, lineHeight: 1.28 }}>{question}</div>{!answer ? <><div style={{ display: "flex", alignItems: "center", gap: 18, marginTop: 30 }}><div style={{ color, fontFamily: CODE_FONT, fontSize: 46, fontWeight: 800 }}>{Math.max(0, Math.ceil((seconds(5) - local) / FPS))}</div><div style={{ color: COLORS.muted, fontSize: 17 }}>不要只说一个关键词，补上为什么。</div></div><div style={{ height: 6, marginTop: 24, borderRadius: 999, backgroundColor: COLORS.border }}><div style={{ height: "100%", width: `${clamp(local, 0, seconds(5)) * 100}%`, backgroundColor: color, borderRadius: 999 }} /></div></> : <div style={{ marginTop: 34, padding: "20px 22px", border: `1px solid ${color}44`, borderRadius: 7, backgroundColor: `${color}10`, color: COLORS.text, fontSize: 21, fontWeight: 750, lineHeight: 1.55, ...reveal(local, seconds(5)) }}>{explanation}</div>}</Card><Card strong style={{ minHeight: 570, padding: "26px 24px" }}><div style={{ color: COLORS.muted, fontFamily: CODE_FONT, fontSize: 12, fontWeight: 800 }}>REVIEW QUEUE</div><div style={{ marginTop: 18, display: "grid", gap: 12 }}>{FOLLOWUPS.map(([item], itemIndex) => <div key={item} style={{ padding: "14px 14px", border: `1px solid ${itemIndex === index ? color : COLORS.border}`, borderRadius: 7, backgroundColor: itemIndex === index ? `${color}10` : "rgba(255,255,255,0.48)", opacity: itemIndex > index ? 0.58 : 1 }}><div style={{ color: itemIndex === index ? color : COLORS.faint, fontFamily: CODE_FONT, fontSize: 12, fontWeight: 800 }}>{String(itemIndex + 1).padStart(2, "0")}</div><div style={{ marginTop: 7, color: COLORS.text, fontSize: 16, lineHeight: 1.4 }}>{item}</div></div>)}</div></Card></div><Caption frame={frame} label="面试追问 · 复述" title="先说声明/定义，再说链接和工程边界" body="把语言规则与模块设计分开回答，比只说‘extern 是跨文件’更完整。" color={color} /></AbsoluteFill>; };

const FINAL_ITEMS = [["extern 的核心作用？", "声明别处定义的变量或函数，让多个编译单元共享同一个符号。", COLORS.accent], ["声明和定义怎么区分？", "声明不创建实体，定义分配空间并创建实体；定义要由工程提供合适的一次。", COLORS.active], ["链接错误怎么排查？", "检查定义数量、extern 声明和头文件位置，区分 duplicate 与 undefined symbol。", COLORS.result], ["最后一个工程边界？", "extern 能连接名字，但不替你解决全局耦合；C++ 接口还要考虑 extern \"C\"。", COLORS.danger]] as const;
const FinalScene: React.FC = () => { const frame = useCurrentFrame(); const unit = seconds(8.5); const index = Math.min(3, Math.floor(frame / unit)); const local = frame - index * unit; const answer = local >= seconds(5.5); const [question, answerText, color] = FINAL_ITEMS[index]; return <AbsoluteFill><TopBar frame={frame} section="第 4 题 / 收束" title="最后一次：不看答案，自己复述" tag="慢速复习 · 0:34" /><SceneTitle frame={frame} eyebrow="记忆收束" title="把 extern 压缩成四个可复述的句子" detail="真正复习完成的标志，是你能同时说清声明、定义、链接错误和工程边界。" /><div style={{ position: "absolute", left: 72, right: 72, top: 306, display: "grid", gridTemplateColumns: "1.1fr 0.9fr", gap: 22 }}><Card strong style={{ minHeight: 565, padding: "32px 38px", borderLeft: `4px solid ${color}` }}><div style={{ color, fontFamily: CODE_FONT, fontSize: 13, fontWeight: 800 }}>FINAL RECALL · {index + 1}/4</div><div style={{ marginTop: 26, color: COLORS.text, fontFamily: DISPLAY_FONT, fontSize: 35, fontWeight: 700, lineHeight: 1.28 }}>{question}</div>{!answer ? <div style={{ marginTop: 28, color: COLORS.muted, fontSize: 17 }}>先停 5.5 秒，再继续。</div> : <div style={{ marginTop: 32, padding: "18px 20px", border: `1px solid ${color}44`, borderRadius: 7, backgroundColor: `${color}10`, color: COLORS.text, fontSize: 21, fontWeight: 750, lineHeight: 1.55, ...reveal(local, seconds(5.5)) }}>{answerText}</div>}</Card><Card strong style={{ minHeight: 565, padding: "26px 24px" }}><div style={{ color: COLORS.muted, fontFamily: CODE_FONT, fontSize: 12, fontWeight: 800 }}>ONE-LINE SUMMARY</div><div style={{ marginTop: 28, color: COLORS.text, fontFamily: DISPLAY_FONT, fontSize: 34, fontWeight: 700 }}>extern = 连接跨文件符号</div><div style={{ marginTop: 22, display: "grid", gap: 12 }}>{[["声明", "告诉编译器符号存在"], ["定义", "真正创建实体"], ["链接", "由链接器完成匹配"]].map(([label, text], itemIndex) => <div key={label} style={{ padding: "15px 16px", border: `1px solid ${itemIndex === index ? color : COLORS.border}`, borderRadius: 7, backgroundColor: itemIndex === index ? `${color}10` : "rgba(255,255,255,0.48)" }}><div style={{ color: itemIndex === index ? color : COLORS.muted, fontFamily: CODE_FONT, fontSize: 12, fontWeight: 800 }}>{label}</div><div style={{ marginTop: 6, color: COLORS.text, fontSize: 17, fontWeight: 700 }}>{text}</div></div>)}</div></Card></div><Caption frame={frame} label="复习完成" title="能说清这四句，第 4 题就真正过了一遍" body="下次复习先回忆‘声明不分配、定义创建实体’，再补链接错误和 extern C。" color={COLORS.result} /></AbsoluteFill>; };

export const ExternQ4Video: React.FC = () => { const frame = useCurrentFrame(); const progress = interpolate(frame, [0, TOTAL_FRAMES - 1], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" }); const starts = { opening: 0, map: SCENE.opening, link: SCENE.opening + SCENE.map, errors: SCENE.opening + SCENE.map + SCENE.link, cpp: SCENE.opening + SCENE.map + SCENE.link + SCENE.errors, followups: SCENE.opening + SCENE.map + SCENE.link + SCENE.errors + SCENE.cpp, final: SCENE.opening + SCENE.map + SCENE.link + SCENE.errors + SCENE.cpp + SCENE.followups }; return <AbsoluteFill style={{ fontFamily: BODY_FONT, color: COLORS.text, overflow: "hidden" }}><Background /><Sequence from={starts.opening} durationInFrames={SCENE.opening}><Opening /></Sequence><Sequence from={starts.map} durationInFrames={SCENE.map}><MapScene /></Sequence><Sequence from={starts.link} durationInFrames={SCENE.link}><LinkScene /></Sequence><Sequence from={starts.errors} durationInFrames={SCENE.errors}><ErrorsScene /></Sequence><Sequence from={starts.cpp} durationInFrames={SCENE.cpp}><CppScene /></Sequence><Sequence from={starts.followups} durationInFrames={SCENE.followups}><FollowupScene /></Sequence><Sequence from={starts.final} durationInFrames={SCENE.final}><FinalScene /></Sequence><div style={{ position: "absolute", left: 58, right: 58, bottom: 22, height: 4, borderRadius: 999, backgroundColor: COLORS.border }}><div style={{ height: "100%", width: `${progress * 100}%`, borderRadius: 999, backgroundColor: COLORS.accent }} /></div><div style={{ position: "absolute", right: 58, bottom: 31, color: COLORS.muted, fontFamily: CODE_FONT, fontSize: 11, fontWeight: 700 }}>Q04 · extern · 3:54</div></AbsoluteFill>; };
export const ExternQ4Composition = () => <Composition id="ExternQ4" component={ExternQ4Video} durationInFrames={TOTAL_FRAMES} fps={FPS} width={1920} height={1080} />;
